/*
	Copyright (c) 2021 Team Tidal

	THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
	IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
	FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
	AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
	LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
	OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
	SOFTWARE.
*/

SWEP.Category = "Split Bullet: Anarchy"
SWEP.Author = "TidalDevs"
SWEP.Contact = "https://discord.gg/XDVCmQzUGW"
SWEP.Purpose = "For use in Split Bullet: Anarchy."
SWEP.DrawWeaponInfoBox = false
SWEP.BounceWeaponIcon = false
SWEP.PrintName = "Split Bullet"
SWEP.Spawnable = true
SWEP.AdminSpawnable = false
